apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share"
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-dns
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share"
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-dns
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53