apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-dev-admin
  namespace: dev
subjects:
- kind: User
  name: jane
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: ""
