apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-the-viewer
  namespace: dev
subjects:
- kind: User
  name: ken
  apiGroup: ""
roleRef:
  kind: Role
  name: view
  apiGroup: ""
