apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share"
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53