apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: prometheus
subjects:
- kind: User
  name: carol
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""
