apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: prometheus
subjects:
- kind: User
  name: carol
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""
