apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-the-admin
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""
