apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-dev
bases:
  - ../../base

resources:
  - namespace.yaml
images:
  - name: gcr.io/google-samples/microservices-demo/recommendationservice
    newTag: gitops-prod
commonLabels:
  env: prod
namePrefix: prod-